# Use postgres/example user/password credentials
version: "3.1"

services:
  lets-go-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    container_name: lets-go-db
    ports:
      - 5432:5432
